### ISSUE TITLE
LiveDisplay color adjustment not working

### ISSUE THREAD

**Issue by pgaskin** [ArrowOS-Devices/android_device_motorola_cedric#1]
The LiveDisplay night mode color temperature adjustment does not work properly in ArrowOS (9.0 official, March 2, 2019). I'm on Nougat FW. LiveDisplay worked fine in LineageOS 15.1.

**Comment by justks** [comment]
LiveDisplay is a LineageOS exclusive feature and it will not work in non LineageOS based projects.
AOSP has night light, and that works well here

**Comment by pgaskin** [comment]
Sorry about the confusion with the naming (I just came from LineageOS). I mean the night mode. It dims the screen, but no color temperature adjustment is made.

**Comment by justks** [comment]
Okay, yea
maybe Cedric vendor doesn't have updated sdm blobs which might be causing it

**Comment by justks** [comment]
Yep, it doesn't 
needs https://github.com/ArrowOS-Devices/android_vendor_motorola_potter/commit/41c82d42bdb939e36e8559d325ca4df4667dd08e

CC: @resk84

**Comment by pgaskin** [comment]
I tested those blobs, and it works well. Maybe it might also be a good idea to keep track of which blobs came from where, like many of the LOS device trees do.

**Comment by pgaskin** [comment]
The new blobs were [pushed](https://github.com/ArrowOS-Devices/android_vendor_motorola_cedric/commit/e2a530edaef1a19848c113276cf657c99b4fe49d) to the vendor repo.
